files:
  # vim
  - src: vim/vimrc
    dst: .vimrc
  # zsh
  - src: zsh/zshrc
    dst: .zshrc
  - src: zsh/zprofile
    dst: .zprofile
  # bash
  - src: bash/bash_logout
    dst: .bash_logout
  - src: bash/bashrc
    dst: .bashrc
  - src: bash/profile
    dst: .profile
  # x
  - src: x/xinitrc
    dst: .xinitrc
  - src: x/Xresources
    dst: .Xresources
  # git
  - src: git/gitconfig
    dst: .gitconfig
  # dunst
  - src: dunst/dunstrc
    dst: .config/dunst/dunstrc
  # i3
  - src: i3/config
    dst: .config/i3/config
  # kitty
  - src: kitty/kitty.conf
    dst: .config/kitty/kitty.conf
  - src: kitty/def.conf
    dst: .config/kitty/colors/def.conf
  # polybar
  - src: polybar/config.ini
    dst: .config/polybar/config.ini
  - src: polybar/launch.sh
    dst: .config/polybar/launch.sh
  - src: polybar/scripts/nvidia-smi-temp.sh
    dst: .config/polybar/scripts/nvidia-smi-temp.sh
  - src: polybar/scripts/nvidia-smi-vram.sh
    dst: .config/polybar/scripts/nvidia-smi-vram.sh
  - src: polybar/scripts/pipewire.sh
    dst: .config/polybar/scripts/pipewire.sh
  - src: polybar/scripts/radeon-gpu.sh
    dst: .config/polybar/scripts/radeon-gpu.sh
  - src: polybar/scripts/system-nvidia-smi.sh
    dst: .config/polybar/scripts/system-nvidia-smi.sh
  # ranger
  - src: ranger/rc.conf
    dst: .config/ranger/rc.conf
  # rofi
  - src: rofi/config.rasi
    dst: .config/rofi/config.rasi
  - src: rofi/theme.rasi
    dst: .config/rofi/theme.rasi
  - src: rofi/theme2.rasi
    dst: .config/rofi/theme2.rasi
  # starship
  - src: starship/starship.toml
    dst: .config/starship.toml